// Generated by scripts/export-public-privacy.py; edit the app policy source.
export const privacyCopy = [
  {
    "english": "1. Scope and operator",
    "chinese": "1. 适用范围与营运者"
  },
  {
    "english": "This policy describes how Cheese handles personal information when you use the iOS app, community, marketplace, profile, notification and chat features. Cheese is the service operator for this policy. Contact: support@cheeseapp.dev.",
    "chinese": "本政策说明你使用 Cheese iOS App、社群、二手、个人档案、通知与聊天功能时，我们如何处理个人资料。本政策中的服务营运者为 Cheese；联络信箱：support@cheeseapp.dev。"
  },
  {
    "english": "2. Information we collect",
    "chinese": "2. 我们搜集的资料"
  },
  {
    "english": "Account data: email address, account identifier, sign-in provider and authentication records from Apple, Google or our authentication provider.",
    "chinese": "帐号资料：Email、帐号识别码，以及 Apple、Google 或验证服务提供者产生的登入与验证纪录。"
  },
  {
    "english": "Profile data: display name, avatar, school, bio, occupation and preferences you choose to provide.",
    "chinese": "个人档案：显示名称、头像、学校、简介、职业及你选择提供的偏好。"
  },
  {
    "english": "Community activity: posts, listings, comments, reactions, favourites, follows, blocks, searches, reports and feedback.",
    "chinese": "社群活动：贴文、刊登、留言、反应、收藏、追踪、封锁、搜寻、举报与回馈。"
  },
  {
    "english": "Messages: direct and group messages, shared media, membership, read state and conversation settings.",
    "chinese": "通讯资料：私讯与群聊内容、分享的媒体、群组成员关系、已读状态与对话设定。"
  },
  {
    "english": "Technical data: IP address and request logs processed by our hosting provider, device or app version, push token, timestamps, security events, cache and basic diagnostic information.",
    "chinese": "技术资料：由托管服务处理的 IP 位址与请求纪录、装置或 App 版本、推播权杖、时间戳记、安全事件、快取与基本诊断资讯。"
  },
  {
    "english": "Optional media: only photos you select through the system photo picker for an avatar, post, listing or message.",
    "chinese": "选用媒体：仅包含你透过系统照片选择器主动选取并用于头像、贴文、刊登或讯息的照片。"
  },
  {
    "english": "3. How and why we use information",
    "chinese": "3. 搜集方式与使用目的"
  },
  {
    "english": "Provide accounts, profiles, posting, search, recommendations, chat, notifications and media delivery.",
    "chinese": "提供帐号、个人档案、发布、搜寻、内容排序、聊天、通知与媒体传输功能。"
  },
  {
    "english": "Remember settings, maintain sessions, synchronize devices and improve reliability and usability.",
    "chinese": "记住设定、维持登入、同步装置，并改善稳定性与易用性。"
  },
  {
    "english": "Prevent spam, fraud, abuse and security incidents; investigate reports and enforce our rules.",
    "chinese": "预防垃圾内容、诈骗、滥用与安全事件；调查举报并执行社群规则。"
  },
  {
    "english": "Respond to support, protect users and comply with valid legal obligations.",
    "chinese": "回应客服需求、保护用户，并履行有效的法律义务。"
  },
  {
    "english": "4. Public and anonymous activity",
    "chinese": "4. 公开内容与匿名活动"
  },
  {
    "english": "Profile fields and content posted to public areas may be viewed, copied, shared or captured by others. Anonymous posting hides the public link to your profile for that post, but Cheese still associates the activity with your account for security, operation and moderation. Do not publish information you want to remain private.",
    "chinese": "个人档案栏位及发布于公开区域的内容，可能被他人查看、复制、分享或截图。匿名发文只会隐藏该贴文与你公开档案的连结；基于营运、安全与管理需要，Cheese 仍会将该活动与你的帐号关联。请勿发布你希望保持私密的资讯。"
  },
  {
    "english": "5. When information is shared",
    "chinese": "5. 资料分享情形"
  },
  {
    "english": "With other users according to the feature and visibility you select, including message recipients and group members.",
    "chinese": "依功能与你选择的可见范围分享给其他用户，包括讯息接收者及群组成员。"
  },
  {
    "english": "With infrastructure and service providers needed to run Cheese, including Supabase for authentication, database, storage and realtime delivery; Apple and Google for sign-in; Apple for push notifications; and Cloudflare for hosting, request delivery and security.",
    "chinese": "分享给维持 Cheese 所需的服务提供者，包括提供验证、资料库、储存与即时传输的 Supabase，提供登入的 Apple 与 Google，提供推播的 Apple，以及提供托管、请求传输与安全服务的 Cloudflare。"
  },
  {
    "english": "With authorized reviewers when content is reported or access is necessary to address safety, fraud, support or rule enforcement.",
    "chinese": "当内容遭举报，或为处理安全、诈骗、客服及规则执行所必要时，提供给经授权的审查人员。"
  },
  {
    "english": "When required by law, valid legal process, an emergency involving safety, or a business reorganization subject to appropriate safeguards.",
    "chinese": "因法律、有效法律程序、涉及安全的紧急情况，或在具备适当保障的业务重组下提供。"
  },
  {
    "english": "The current version of Cheese does not sell personal information or use cross-app tracking for targeted advertising.",
    "chinese": "目前版本的 Cheese 不贩售个人资料，也不使用跨 App 追踪进行定向广告。"
  },
  {
    "english": "AI processing permission",
    "chinese": "AI 处理权限"
  },
  {
    "english": "With your explicit account permission, Google Gemini processes your forum text for semantic recommendations, consented discussion text and up to three post images for AI replies, selected listing images and entered listing details for optional descriptions, and uploaded images for content safety checks before publication. Declining keeps browsing and text-only features available; image uploads require safety processing. Withdraw permission in Settings to stop new transfers and remove your recommendation vectors.",
    "chinese": "经你明确同意后，Google Gemini 会处理你的论坛文字以提供语义推荐、经相关作者同意的讨论文字及最多三张贴文图片以生成 AI 回复、所选商品图片与填写的商品资料以生成可选简介，以及上传图片以在发布前检查内容安全。拒绝后仍可浏览并使用纯文字功能；图片上传需要安全处理。你可在设定撤回同意，停止新的传输并移除你的推荐向量。"
  },
  {
    "english": "Google processes requests under its Gemini API terms. Provider retention, review and model-improvement use depend on the applicable service and billing terms; Cheese does not promise zero provider retention. Processing may occur outside Canada. Avoid sending sensitive personal information. Contact support@cheeseapp.dev for deletion requests, provider information or concerns about a safety decision.",
    "chinese": "Google 依 Gemini API 条款处理请求；服务商的保留、审查及模型改进用途取决于适用服务与计费条款，Cheese 不承诺服务商完全不保留资料。处理地点可能在加拿大境外。请勿传送敏感个人资料。如需删除资料、了解服务商资讯或申请复核安全判定，请联络 support@cheeseapp.dev。"
  },
  {
    "english": "6. Storage, retention and account deletion",
    "chinese": "6. 储存、保留与帐号注销"
  },
  {
    "english": "We retain information while your account is active and as reasonably necessary to provide the service, resolve disputes, prevent abuse and meet legal obligations. Retention varies by data type and context.",
    "chinese": "帐号有效期间内，我们会保留提供服务所需的资料；为解决争议、防止滥用及履行法律义务，也可能在合理必要期间内继续保留。实际期间依资料类型与情境而异。"
  },
  {
    "english": "Using Delete Account removes your public posts and account activity covered by the deletion process, revokes sign-in identities and de-identifies the profile. Original email, profile contact details, identity metadata and sign-in credentials are erased. A disabled authentication tombstone and de-identified profile remain so existing chats can show “Deactivated”. Avatar and cover objects enter a retryable deletion queue; this storage cleanup can finish after the account screen closes. Messages already delivered, reports, security records, backups and copies retained by other users may remain where necessary or outside our control.",
    "chinese": "使用「注销帐号」后，系统会移除注销流程涵盖的公开贴文与帐号活动、撤销登入身分，并将个人档案去识别化。原始 Email、个人联系方式、身分资料与登入凭证会被清除。为让既有聊天显示「已注销」，系统会保留停用的验证替代纪录及去识别化档案；头像与封面会进入可重试删除队列，储存清理可能在帐号画面关闭后完成。已送达的讯息、举报、安全纪录、备份，以及他人自行保存的副本，可能因必要性或超出我们控制而继续存在。"
  },
  {
    "english": "7. Your choices and rights",
    "chinese": "7. 你的选择与权利"
  },
  {
    "english": "Edit profile information and choose anonymity independently for each forum post.",
    "chinese": "编辑个人档案，并为每篇论坛贴文独立选择是否匿名。"
  },
  {
    "english": "Control push notifications, block users, hide messages for yourself and clear local image cache in Settings.",
    "chinese": "在设定中控制推播、封锁用户、仅为自己隐藏讯息，并清除本机图片快取。"
  },
  {
    "english": "Delete your account from Settings.",
    "chinese": "从设定中注销帐号。"
  },
  {
    "english": "Request access, correction, deletion, restriction or portability where applicable by emailing support@cheeseapp.dev. We may verify your identity first.",
    "chinese": "在适用法律允许的范围内，可寄信至 support@cheeseapp.dev 请求查阅、更正、删除、限制处理或取得可携副本；我们可能先验证你的身分。"
  },
  {
    "english": "8. Children",
    "chinese": "8. 未成年人"
  },
  {
    "english": "Cheese is not for children under 13. If local law requires a higher minimum age or parental consent, that rule applies. Contact us if you believe a child provided information contrary to this requirement.",
    "chinese": "Cheese 不提供给未满 13 岁的儿童使用。若所在地法律要求更高的最低年龄或监护人同意，则以该规定为准。若你认为有儿童违反此要求提供资料，请联络我们。"
  },
  {
    "english": "9. Security and international processing",
    "chinese": "9. 安全与跨境处理"
  },
  {
    "english": "We use access controls, row-level authorization, private media storage and other reasonable safeguards. No online service can guarantee absolute security. Service providers may process information outside your province or country, where different laws may apply.",
    "chinese": "我们使用存取控制、资料列层级授权、私人媒体储存及其他合理保障；但任何线上服务都无法保证绝对安全。服务提供者可能在你所在省份或国家以外处理资料，并受当地法律规范。"
  },
  {
    "english": "10. Updates and contact",
    "chinese": "10. 更新与联络方式"
  },
  {
    "english": "We may update this policy as Cheese changes. Material changes will be communicated in the app or through another reasonable channel before they take effect where required. Questions or privacy requests: support@cheeseapp.dev.",
    "chinese": "我们可能随 Cheese 功能调整而更新本政策。若有重大变更，会在法律要求的情况下，于生效前透过 App 或其他合理方式通知。政策问题或隐私请求：support@cheeseapp.dev。"
  }
];
