// Generated by scripts/export-public-privacy.py; edit the app policy source.
export const privacyCopy = [
  {
    "english": "1. Scope and operator",
    "chinese": "1. 适用范围与营运者"
  },
  {
    "english": "This policy describes how Cheese handles personal information when you use the iOS app, community, marketplace, profile, notification and chat features. Cheese is the service operator for this policy. Contact: support.cheeseteam@gmail.com.",
    "chinese": "本政策说明你使用 Cheese iOS App、社群、二手、个人档案、通知与聊天功能时，我们如何处理个人资料。本政策中的服务营运者为 Cheese；联络信箱：support.cheeseteam@gmail.com。"
  },
  {
    "english": "2. Information we collect",
    "chinese": "2. 我们搜集的资料"
  },
  {
    "english": "Account data: email address, account identifier, sign-in provider and authentication records from Apple, Google or our authentication provider.",
    "chinese": "帐号资料：Email、帐号识别码，以及 Apple、Google 或验证服务提供者产生的登入与验证纪录。"
  },
  {
    "english": "Profile data: display name, avatar, school, required gender selection (including the option to prefer not to say), bio, occupation and preferences you choose to provide.",
    "chinese": "个人档案：显示名称、头像、学校、必填的性别选项（包括「暂不透露」）、简介、职业及你选择提供的偏好。"
  },
  {
    "english": "Social activity: follows, blocks and group membership, which form your in-app social graph. Community activity: posts, comments, reactions, favourites, searches, reports and feedback.",
    "chinese": "社交活动：追踪、封锁与群组成员关系，构成你在 App 内的社交关系图谱。社群活动：贴文、留言、反应、收藏、搜寻、举报与回馈。"
  },
  {
    "english": "Marketplace activity: listings, purchase intents, completed transaction history, prices and buyer or seller role.",
    "chinese": "二手交易活动：刊登、购买意向、已完成交易纪录、价格及买家或卖家角色。"
  },
  {
    "english": "Messages: direct and group messages, shared media, membership, read state and conversation settings.",
    "chinese": "通讯资料：私讯与群聊内容、分享的媒体、群组成员关系、已读状态与对话设定。"
  },
  {
    "english": "Technical data: IP address and request logs processed by our hosting provider, device or app version, push token, timestamps, security events, cache and basic diagnostic information.",
    "chinese": "技术资料：由托管服务处理的 IP 位址与请求纪录、装置或 App 版本、推播权杖、时间戳记、安全事件、快取与基本诊断资讯。"
  },
  {
    "english": "Optional media: only photos you select through the system photo picker for an avatar, post, listing or message.",
    "chinese": "选用媒体：仅包含你透过系统照片选择器主动选取并用于头像、贴文、刊登或讯息的照片。"
  },
  {
    "english": "3. How and why we use information",
    "chinese": "3. 搜集方式与使用目的"
  },
  {
    "english": "Provide accounts, profiles, posting, search, recommendations, chat, notifications and media delivery.",
    "chinese": "提供帐号、个人档案、发布、搜寻、内容排序、聊天、通知与媒体传输功能。"
  },
  {
    "english": "Remember settings, maintain sessions, synchronize devices and improve reliability and usability.",
    "chinese": "记住设定、维持登入、同步装置，并改善稳定性与易用性。"
  },
  {
    "english": "Prevent spam, fraud, abuse and security incidents; investigate reports and enforce our rules.",
    "chinese": "预防垃圾内容、诈骗、滥用与安全事件；调查举报并执行社群规则。"
  },
  {
    "english": "Respond to support, protect users and comply with valid legal obligations.",
    "chinese": "回应客服需求、保护用户，并履行有效的法律义务。"
  },
  {
    "english": "4. Public and anonymous activity",
    "chinese": "4. 公开内容与匿名活动"
  },
  {
    "english": "Profile fields and content posted to public areas may be viewed, copied, shared or captured by others. Anonymous posting hides the public link to your profile for that post, but Cheese still associates the activity with your account for security, operation and moderation. Do not publish information you want to remain private.",
    "chinese": "个人档案栏位及发布于公开区域的内容，可能被他人查看、复制、分享或截图。匿名发文只会隐藏该贴文与你公开档案的连结；基于营运、安全与管理需要，Cheese 仍会将该活动与你的帐号关联。请勿发布你希望保持私密的资讯。"
  },
  {
    "english": "5. When information is shared",
    "chinese": "5. 资料分享情形"
  },
  {
    "english": "With other users according to the feature and visibility you select, including message recipients and group members.",
    "chinese": "依功能与你选择的可见范围分享给其他用户，包括讯息接收者及群组成员。"
  },
  {
    "english": "With infrastructure and service providers needed to run Cheese, including Supabase for authentication, database, storage and realtime delivery; Apple and Google for sign-in; Apple for push notifications; and Cloudflare for hosting, request delivery and security.",
    "chinese": "分享给维持 Cheese 所需的服务提供者，包括提供验证、资料库、储存与即时传输的 Supabase，提供登入的 Apple 与 Google，提供推播的 Apple，以及提供托管、请求传输与安全服务的 Cloudflare。"
  },
  {
    "english": "With authorized reviewers when content is reported or access is necessary to address safety, fraud, support or rule enforcement.",
    "chinese": "当内容遭举报，或为处理安全、诈骗、客服及规则执行所必要时，提供给经授权的审查人员。"
  },
  {
    "english": "When required by law, valid legal process, an emergency involving safety, or a business reorganization subject to appropriate safeguards.",
    "chinese": "因法律、有效法律程序、涉及安全的紧急情况，或在具备适当保障的业务重组下提供。"
  },
  {
    "english": "The current version of Cheese does not sell personal information or use cross-app tracking for targeted advertising.",
    "chinese": "目前版本的 Cheese 不贩售个人资料，也不使用跨 App 追踪进行定向广告。"
  },
  {
    "english": "Media safety review and optional AI",
    "chinese": "图片安全审核与可选 AI"
  },
  {
    "english": "Before an image is published, Cheese sends the selected image to Cloudflare Workers AI for automated safety review. This required review may process content outside Canada. Cloudflare says it does not use input or output to train or improve its models without consent. You may decline, or withdraw the local image-review acknowledgement in Settings, and continue using features that do not upload images. Do not include sensitive personal information.",
    "chinese": "图片发布前，Cheese 会将选中的图片交给 Cloudflare Workers AI 自动检查不当内容。这项必要审核的处理地点可能在加拿大境外。Cloudflare 表示未经同意不会使用输入或输出内容来训练或改进模型。你可以拒绝，或在设定中撤回本机图片审核确认，并继续使用不需上传图片的功能；请勿包含敏感个人资料。"
  },
  {
    "english": "Optional Google Gemini features are not available in this release. If Cheese restores them in a future release, it will obtain separate account permission before sending forum text, listing details or images. Declining or withdrawing that separate permission will stop new optional transfers and remove pending embedding work, authored embeddings and the associated recommendation vector. Contact support.cheeseteam@gmail.com for deletion requests, provider information or a review of a safety decision.",
    "chinese": "本版本未提供可选的 Google Gemini 功能。若 Cheese 在未来版本恢复这些功能，会在传送论坛文字、商品资料或图片前另外取得帐号同意。拒绝或撤回该独立同意会停止新的可选传输，并删除待处理嵌入工作、已建立的本人嵌入资料及相关的推荐向量。如需删除资料、了解服务商资讯或申请复核安全处置，请联络 support.cheeseteam@gmail.com。"
  },
  {
    "english": "6. Storage, retention and account deletion",
    "chinese": "6. 储存、保留与帐号注销"
  },
  {
    "english": "We retain information while your account is active and as reasonably necessary to provide the service, resolve disputes, prevent abuse and meet legal obligations. Retention varies by data type and context.",
    "chinese": "帐号有效期间内，我们会保留提供服务所需的资料；为解决争议、防止滥用及履行法律义务，也可能在合理必要期间内继续保留。实际期间依资料类型与情境而异。"
  },
  {
    "english": "Using Delete Account removes your posts, listings, comments, direct and group-message content, and associated media from Cheese’s active systems; brief de-identified delivery tombstones may remain only to preserve conversation structure. Original email, profile contact details, identity metadata and sign-in credentials are erased. When the matching Google Sign-In session is present on this device, Cheese asks Google to disconnect it. Sign in with Apple authorization is managed by Apple and may remain in your Apple Account’s Sign in with Apple list until you remove Cheese there. Avatar, cover, post, chat and Content Studio draft objects enter a retryable deletion queue; this storage cleanup can finish after the account screen closes. We do not retain your original message text or photos in those tombstones. We cannot retrieve material another person separately saved or external notifications already delivered; legally required records and protected backups follow their applicable retention rules.",
    "chinese": "使用「注销帐号」会从 Cheese 的运作中系统移除你的贴文、刊登、评论、私讯与群聊内容，以及相关媒体；为维持对话结构，可能只保留不含原始内容的去识别化投递替代纪录。原始 Email、个人联系方式、身分资料与登入凭证会被清除。若本机存在相符的 Google 登录工作阶段，Cheese 会请求 Google 解除该授权；Apple 登录授权由 Apple 管理，在你于 Apple 帐号的「使用 Apple 登录」中移除 Cheese 前，可能仍会显示。头像、封面、贴文、聊天和 Content Studio 草稿对象会进入可重试删除队列，储存清理可能在帐号画面关闭后完成。我们不会在这些替代纪录中保留你原始的讯息文字或照片。我们无法收回他人另行保存的资料或已经送达的外部通知；依法必须保留的纪录和受保护备份依适用保留规则处理。"
  },
  {
    "english": "7. Your choices and rights",
    "chinese": "7. 你的选择与权利"
  },
  {
    "english": "Edit profile information and choose anonymity independently for each forum post.",
    "chinese": "编辑个人档案，并为每篇论坛贴文独立选择是否匿名。"
  },
  {
    "english": "Control push notifications, block users, hide messages for yourself and clear local image cache in Settings.",
    "chinese": "在设定中控制推播、封锁用户、仅为自己隐藏讯息，并清除本机图片快取。"
  },
  {
    "english": "Delete your account from Settings.",
    "chinese": "从设定中注销帐号。"
  },
  {
    "english": "Request access, correction, deletion, restriction or portability where applicable by emailing support.cheeseteam@gmail.com. We may verify your identity first.",
    "chinese": "在适用法律允许的范围内，可寄信至 support.cheeseteam@gmail.com 请求查阅、更正、删除、限制处理或取得可携副本；我们可能先验证你的身分。"
  },
  {
    "english": "8. Children",
    "chinese": "8. 未成年人"
  },
  {
    "english": "Cheese is not for children under 13. If local law requires a higher minimum age or parental consent, that rule applies. Contact us if you believe a child provided information contrary to this requirement.",
    "chinese": "Cheese 不提供给未满 13 岁的儿童使用。若所在地法律要求更高的最低年龄或监护人同意，则以该规定为准。若你认为有儿童违反此要求提供资料，请联络我们。"
  },
  {
    "english": "9. Security and international processing",
    "chinese": "9. 安全与跨境处理"
  },
  {
    "english": "We use access controls, row-level authorization, private media storage and other reasonable safeguards. No online service can guarantee absolute security. Service providers may process information outside your province or country, where different laws may apply.",
    "chinese": "我们使用存取控制、资料列层级授权、私人媒体储存及其他合理保障；但任何线上服务都无法保证绝对安全。服务提供者可能在你所在省份或国家以外处理资料，并受当地法律规范。"
  },
  {
    "english": "10. Updates and contact",
    "chinese": "10. 更新与联络方式"
  },
  {
    "english": "We may update this policy as Cheese changes. Material changes will be communicated in the app or through another reasonable channel before they take effect where required. Questions or privacy requests: support.cheeseteam@gmail.com.",
    "chinese": "我们可能随 Cheese 功能调整而更新本政策。若有重大变更，会在法律要求的情况下，于生效前透过 App 或其他合理方式通知。政策问题或隐私请求：support.cheeseteam@gmail.com。"
  }
];
