BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path=public,extensions,pg_temp;
SELECT no_plan();
INSERT INTO auth.users(id,email) VALUES ('52718000-0000-4000-8000-000000000001','school-required@test.invalid');
SELECT ok(NOT profile_completed,'new user remains incomplete despite routing fallback') FROM profiles WHERE id='52718000-0000-4000-8000-000000000001';
SELECT set_config('request.jwt.claim.role','authenticated',true);
SELECT set_config('request.jwt.claims','{"sub":"52718000-0000-4000-8000-000000000001","role":"authenticated"}',true);
SET LOCAL ROLE authenticated;
SELECT throws_ok($q$SELECT complete_profile('Test',NULL,'prefer_not_to_say')$q$,'22023','School is required for students','missing school rejected');
SELECT throws_ok($q$SELECT complete_profile('Test','   ','prefer_not_to_say')$q$,'22023','School is required for students','whitespace school rejected');
SELECT throws_ok($q$SELECT complete_profile('Test','Unknown School','prefer_not_to_say')$q$,'22023','Select a supported school','unknown school rejected');
SELECT throws_ok($q$UPDATE profiles SET profile_completed=true WHERE id=auth.uid()$q$,'42501',NULL,'direct write cannot bypass required completion RPC');
SELECT lives_ok($q$SELECT complete_profile('Test',' york university ','prefer_not_to_say')$q$,'explicit supported school completes registration');
RESET ROLE;
SELECT is((SELECT university FROM profiles WHERE id=auth.uid()),'York University','school name canonicalized');
SELECT is((SELECT school_id FROM profiles WHERE id=auth.uid()),(SELECT id FROM schools WHERE name='York University'),'actual recommendation school matches selected name');
SELECT ok((SELECT p.profile_completed AND (p.campus_id IS NULL OR c.school_id=p.school_id) FROM profiles p LEFT JOIN school_campuses c ON c.id=p.campus_id WHERE p.id=auth.uid()),'completed state and campus match');
SET LOCAL ROLE authenticated;
SELECT throws_ok($q$UPDATE profiles SET university='' WHERE id=auth.uid()$q$,'23514',NULL,'completed school cannot be cleared');
SELECT throws_ok($q$UPDATE profiles SET university='McMaster University' WHERE id=auth.uid()$q$,'23514',NULL,'name-only mismatched school cannot bypass routing');
SELECT lives_ok($q$SELECT complete_profile('Test','McMaster University','prefer_not_to_say')$q$,'valid selection can move to McMaster');
RESET ROLE;
SELECT is((SELECT school_id FROM profiles WHERE id=auth.uid()),(SELECT id FROM schools WHERE name='McMaster University'),'McMaster selection persists correct ID');
SELECT lives_ok($q$UPDATE profiles SET university='已注销',deactivated_at=now() WHERE id=auth.uid()$q$,'deactivation redaction remains supported');
SELECT is((SELECT university FROM profiles WHERE id=auth.uid()),'已注销','deactivated school redaction retained');
SET LOCAL ROLE authenticated;
SELECT throws_ok($q$SELECT complete_profile('Test','McMaster University','prefer_not_to_say')$q$,'P0002','Active profile not found','completion cannot reactivate deleted profile');
SELECT throws_ok('SELECT * FROM school_selection_private.mcmaster_backfill_backup','42501',NULL,'backup is not exposed to client');
RESET ROLE;
SELECT * FROM finish();
ROLLBACK;
