#!/bin/sh

set -eu

usage() {
    echo "Usage: $0 --from-worker /path/to/wrangler.toml" >&2
    echo "   or: SUPABASE_URL=... SUPABASE_PUBLISHABLE_KEY=... $0" >&2
}

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH= cd -- "$script_dir/.." && pwd)
output_file="$repo_dir/CheeseApp/Configuration/Local.xcconfig"

if [ -e "$output_file" ]; then
    echo "Local.xcconfig already exists; refusing to overwrite local configuration." >&2
    exit 73
fi

read_toml_value() {
    key=$1
    file=$2
    awk -v key="$key" '
        $0 ~ "^[[:space:]]*" key "[[:space:]]*=" {
            value = $0
            sub("^[[:space:]]*" key "[[:space:]]*=[[:space:]]*", "", value)
            sub(/[[:space:]]*#.*$/, "", value)
            gsub(/^[[:space:]]*\"|\"[[:space:]]*$/, "", value)
            print value
            exit
        }
    ' "$file"
}

if [ "${1:-}" = "--from-worker" ]; then
    [ "$#" -eq 2 ] || { usage; exit 64; }
    worker_config=$2
    [ -f "$worker_config" ] || {
        echo "Worker configuration is not a regular file: $worker_config" >&2
        exit 66
    }
    supabase_url=$(read_toml_value SUPABASE_URL "$worker_config")
    publishable_key=$(read_toml_value SUPABASE_PUBLISHABLE_KEY "$worker_config")
elif [ "$#" -eq 0 ]; then
    supabase_url=${SUPABASE_URL:-}
    publishable_key=${SUPABASE_PUBLISHABLE_KEY:-}
else
    usage
    exit 64
fi

case "$supabase_url" in
    https://*) ;;
    *)
        echo "SUPABASE_URL must be a non-empty HTTPS URL." >&2
        exit 65
        ;;
esac

case "$publishable_key" in
    ''|*[!A-Za-z0-9._-]*)
        echo "SUPABASE_PUBLISHABLE_KEY is missing or contains unsupported characters." >&2
        exit 65
        ;;
esac

escaped_url=$(printf '%s' "$supabase_url" | sed 's#://#:/$()/#')
umask 077
temp_file=$(mktemp "$repo_dir/CheeseApp/Configuration/.Local.xcconfig.XXXXXX")
trap 'rm -f "$temp_file"' EXIT HUP INT TERM

{
    echo "// Generated by scripts/configure-ios-local.sh; do not commit."
    printf 'SUPABASE_URL = %s\n' "$escaped_url"
    printf 'SUPABASE_PUBLISHABLE_KEY = %s\n' "$publishable_key"
} > "$temp_file"

mv "$temp_file" "$output_file"
trap - EXIT HUP INT TERM
echo "Created ignored local iOS configuration at CheeseApp/Configuration/Local.xcconfig."
