#!/usr/bin/env python3
"""Generate public policy copy from the app's bilingual source (no independent drift)."""
from pathlib import Path
import json
import re
root = Path(__file__).resolve().parents[1]
source = (root/'CheeseApp/CheeseApp/Features/Profile/Views/LegalDocumentViews.swift').read_text()
section = source.split('private static let privacySections: [LegalSection] = [',1)[1].split('private static let agreementSections:',1)[0]
pairs = re.findall(r'\.init\(\s*"((?:\\.|[^"\\])*)"\s*,\s*"((?:\\.|[^"\\])*)"\s*\)', section)
rows = [{'english':json.loads('"'+en+'"'), 'chinese':json.loads('"'+zh+'"')} for en,zh in pairs]
assert len(rows) > 20
(root/'cheeseapp-share-worker/src/pages/legalContent.js').write_text('// Generated by scripts/export-public-privacy.py; edit the app policy source.\nexport const privacyCopy = '+json.dumps(rows,ensure_ascii=False,indent=2)+';\n')
print('Exported bilingual privacy copy:',len(rows),'paragraphs/headings')
